name: 'Create release'
description: 'Create releases for tags'

runs:
  using: "composite"
  steps:
    - name: Set Tag Name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      # trim prefix from ref to get tag name
      run: echo "TAG_NAME=${GITHUB_REF#'refs/tags/'}" >> ${GITHUB_ENV}

    - name: Add tag to folder name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv ${{ env.ZIP_NAME }} ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}

    - name: Add AppImage
      shell: bash
      if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
      run: |
        cp ${{ env.BUILD_DIR }}/${{ env.EXECUTABLE_NAME }}.AppImage ${{ env.EXECUTABLE_NAME }}_${{ env.TAG_NAME }}_${{ env.BUILD_TYPE }}${{ matrix.asan_name }}.AppImage

    - name: Add Windows installer
      shell: bash
      if: runner.os == 'Windows' && (matrix.cxx == 'g++') # || contains(env.BUILD_TYPE, 'Rel'))
      run: |
          cp ${{ env.EXECUTABLE_NAME }}-*-win64.exe ${{ env.EXECUTABLE_NAME }}_${{ env.TAG_NAME }}_${{ env.BUILD_TYPE }}_${{ matrix.cxx }}${{ matrix.asan_name }}.exe

    - name: Add macOS installer
      shell: bash
      if: runner.os == 'macOS'
      run: |
          cp "${{ env.EXECUTABLE_NAME }}.dmg" ${{ env.EXECUTABLE_NAME }}_${{ env.TAG_NAME }}_${{ env.BUILD_TYPE }}_${{ matrix.cxx }}${{ matrix.asan_name }}.dmg

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: 'zip'
        path: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}
        filename: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip

    - name: Generate artifact attestation and upload to release (zip)
      uses: ./.github/actions/create-release-common
      with:
        file: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip

    - name: Generate artifact attestation and upload to release (AppImage)
      uses: ./.github/actions/create-release-common
      if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
      with:
        file: ${{ env.EXECUTABLE_NAME }}_${{ env.TAG_NAME }}_${{ env.BUILD_TYPE }}${{ matrix.asan_name }}.AppImage

    - name: Generate artifact attestation and upload to release (Windows installer)
      uses: ./.github/actions/create-release-common
      if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Windows' && matrix.cxx == 'g++'
      with:
        file: ${{ env.EXECUTABLE_NAME }}_${{ env.TAG_NAME }}_${{ env.BUILD_TYPE }}_${{ matrix.cxx }}${{ matrix.asan_name }}.exe

    - name: Generate artifact attestation and upload to release (macOS installer)
      uses: ./.github/actions/create-release-common
      if: startsWith(github.ref, 'refs/tags/') && runner.os == 'macOS'
      with:
        file: ${{ env.EXECUTABLE_NAME }}_${{ env.TAG_NAME }}_${{ env.BUILD_TYPE }}_${{ matrix.cxx }}${{ matrix.asan_name }}.dmg
